CREATE DATABASE alromosdb;
GO
EXEC sp_configure 'CONTAINED DATABASE AUTHENTICATION', 1
GO
RECONFIGURE
GO
USE [master]
GO
ALTER DATABASE [alromosdb] SET CONTAINMENT = PARTIAL
GO

USE alromosdb;

-- alromos DBA user
CREATE USER $(DBA_USER) WITH PASSWORD = '$(DBA_PASSWORD)';
ALTER USER $(DBA_USER) WITH DEFAULT_SCHEMA = Alromos;
GRANT SELECT, INSERT, UPDATE ON SCHEMA :: dbo TO $(DBA_USER);
GRANT CREATE TABLE to $(DBA_USER);

-- alromos application user
CREATE USER $(APP_USER) WITH PASSWORD = '$(APP_PASSWORD)';
ALTER USER $(APP_USER) WITH DEFAULT_SCHEMA = Alromos;

GO
CREATE SCHEMA Alromos AUTHORIZATION $(DBA_USER);

GO
EXECUTE AS USER = '$(DBA_USER)';

GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA :: Alromos TO $(APP_USER);
