input {
  jdbc {
    id => "readNumberFromDb"
    jdbc_driver_class => "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    jdbc_connection_string => "${CONN_STR}"
    jdbc_user => "${JDBC_USER}"
    lowercase_column_names => false
    clean_run => false
    connection_retry_attempts => 5
    schedule => "28 * * * * *"
    statement => "
      SELECT
        TN.TestNumberID AS id,
        TN.Description AS description
      FROM
        Alromos.TestNumber TN
      WHERE
        TN.TestNumberID = 14
    "
  }
}

output {
  elasticsearch {
    id => "writeNumberToElastic"
    hosts => ["${ELASTIC_URL}"]
    document_id => "%{id}"
    retry_on_conflict => 5
    index => "test-number"
    template => "/usr/share/logstash/alromos/template/test-number.json"
    template_name => "test-number"
  }
}
